### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by pinpins** [kumacoinproject/kumacoin#27]
make -f makefile.unix -j4

Ubuntu 16.04

et.h:181:13: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
         for(auto point : points)
             ^
net.h:181:18: error: ‘point’ does not name a type
         for(auto point : points)
                  ^
net.h:187:9: error: expected ‘;’ before ‘double’
         double nAvgValue = (double)nBlocks / size;
         ^
net.h:190:9: error: expected primary-expression before ‘bool’
         bool banNode = (nAvgValue >= 1.5 * maxAvg && size >= maxAvg) ||

**Comment by namuyan** [comment]
http://h2a.sakura.ne.jp/kumawiki/index.php?Kumacoin-Qt%20Wallet%20for%20Ubuntu
Let's try `make -f makefile.unix -j4 EXT_OPTIONS='-std=c++11'`
