### ISSUE TITLE
listtransactions empty

### ISSUE THREAD

**Issue by crackfoo** [kumacoinproject/kumacoin#6]
Hi, 

When mining and blocks are found, they are not seen in list transactions. Any clues why?

Thanks

**Comment by namuyan** [comment]
Hello, are you in trouble kumacoin yiimp pool?
Do you meam that you cannot seen any PoW mined transactions by `listtransactions` command?

**Comment by crackfoo** [comment]
Yes that’s right. Any idea why that is?

Thanks

**Comment by namuyan** [comment]
Generated block undisplayed. [rpcwallet.cpp#L1004](https://github.com/kumacoinproject/kumacoin/blob/master/src/rpcwallet.cpp#L1004)
Please wait....

**Comment by namuyan** [comment]
How about remove commet out?
[miningbeaver pool](https://miningbeaver.ga/) report fix the problem.
